[package]
name = "xml_dom_xpath"
version = "0.1.0"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
edition = "2018"


[dependencies]
#xml_dom = "0.2.1"
xml_dom = { version="0.2", path="../xml_dom" }
lazy_static = "1.4.0"
pest = "2.0"
pest_derive = "2.0"